"""rename question author to author field

Revision ID: 2caee442b69e
Revises: 8a48cb6fe7d4
Create Date: 2025-08-21 11:02:13.813057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2caee442b69e'
down_revision: Union[str, Sequence[str], None] = '8a48cb6fe7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('author', sa.String(), nullable=True))
    op.drop_column('questions', 'question_author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'author')
    # ### end Alembic commands ###
