"""add author field

Revision ID: 8a48cb6fe7d4
Revises: 29516bc577c5
Create Date: 2025-08-21 10:40:19.080697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a48cb6fe7d4'
down_revision: Union[str, Sequence[str], None] = '29516bc577c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_author')
    # ### end Alembic commands ###
