"""Add Role in User

Revision ID: a157867e866e
Revises: a2a163d1fcc3
Create Date: 2025-09-03 07:57:29.538284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a157867e866e'
down_revision: Union[str, Sequence[str], None] = 'a2a163d1fcc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum =postgresql.ENUM('ADMIN', 'OPERATOR', 'MANAGER', name='user_role')
    role_enum.create(op.get_bind())
    op.add_column('users', sa.Column('role', role_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
